# @(#) Ports of CXX library
# Author Andrew Wingorodov <http://andr.mobi/>
# Licence: LGPLv3
# $Id: Makefile 308 2008-02-14 10:57:53Z wingorodov $

.PHONY: all install doc clean clear distfile

PREFIX?= /usr/local
INCLUDIR= $(PREFIX)/include/libcxx
LIBDIR= $(PREFIX)/lib
INSTALL= install
DISTNAME= libcxx
BUILD= 1.5

all:
	make -f Makefile.old -C src 

install:
	mkdir -p $(INCLUDIR)
	$(INSTALL) src/db/client/db_cli.hpp $(INCLUDIR)
	$(INSTALL) src/db/client/mc_client.hpp $(INCLUDIR)
	$(INSTALL) src/db/client/myquery.hpp $(INCLUDIR)
	$(INSTALL) src/db/client/mysqlcli.hpp $(INCLUDIR)
	$(INSTALL) src/db/client/selquery.hpp $(INCLUDIR)
	$(INSTALL) src/static/singleton.hpp $(INCLUDIR)
	$(INSTALL) src/env/ment.hpp $(INCLUDIR)
	$(INSTALL) src/env/iron.h $(INCLUDIR)
	$(INSTALL) src/except/er.h $(INCLUDIR)
	$(INSTALL) src/except/report.h $(INCLUDIR)
	$(INSTALL) src/logostream/logostream.hpp $(INCLUDIR)
	$(INSTALL) src/timeter/timeter.h $(INCLUDIR)
	$(INSTALL) src/libcxx.a $(LIBDIR)
	$(INSTALL) src/libcxx.so $(LIBDIR)/libcxx.so.1
	ln -sf $(LIBDIR)/libcxx.so.1 $(LIBDIR)/libcxx.so

distfile:
	cd ../tags && \
	tar cvf $(DISTNAME)-$(BUILD).tar --exclude=.svn $(DISTNAME)-$(BUILD)/ &&\
	gzip -9 $(DISTNAME)-$(BUILD).tar && \
	mv $(DISTNAME)-$(BUILD).tar.gz /usr/ports/distfiles

doc:
	make -f Makefile.old -C doc

clean:
	cd ../tags/ && rm -rfv *.tar *.gz *.tgz
	make -f Makefile.old -C src clean
	make -f Makefile.old -C doc clean
