# @(#) Build Env Iron
# @(#) Licence: LGPLv3
# @(#) Author: Andrew Wingorodov <http://andr.ru/>
# $Id: Makefile,v 1.1.1.1 2007-12-20 15:53:44 wingorodov Exp $


CXXFLAGS+= -I.\
		   -I../err\
		   -I../env\
		   -I../logostream

OBJS= example.o args.o proc.o tsk.o\
		 ../logostream/logostream.o\
		 ../env/iron.o

TARGET= example

include /etc/default/mk

../logostream/logostream.o:
	make -f Makefile.old -C ../logostream logostream.o

../env/iron.o:
	make -f Makefile.old -C ../env iron.o

clean clear:
	rm -rfv $(TARGET) *.o *.core
