# @(#) Build log stream
# @(#) Author Andrew Wingorodov <http://andr.ru/>
# $Id: Makefile,v 1.1.1.1 2007-12-20 15:53:44 wingorodov Exp $


CXXFLAGS+= -I.
TARGET=example
OBJS= example.o logostream.o

include /etc/default/mk

clean clear:
	rm -rfv $(TARGET) *.o *.core
